#version: '3.9'
#
#services:
#  db:
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_DB: post
#      POSTGRES_USER: post
#      POSTGRES_PASSWORD: post
#    ports:
#      - "5432:5432"

# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: pg-docker
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: borisshavrin
    ports:
      - 5400:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080